CREATE SEQUENCE BOARD_SEQ INCREMENT BY 1 START WITH 1 NOCACHE NOCYCLE

CREATE TABLE BMEMBER (
	MNO NUMBER(10) PRIMARY KEY,
	ID VARCHAR2(10) NOT NULL,
	PW VARCHAR2(12) NOT NULL,
	NICK VARCHAR2(20) NOT NULL,
	PHONE VARCHAR2(11) NOT NULL,
	REGIST DATE DEFAULT SYSDATE NOT NULL,
	CTL VARCHAR2(10)
	)
SELECT * FROM BMEMBER
DROP  TABLE BMEMBER
INSERT INTO BMEMBER (MNO, ID, PW, NICK, PHONE, CTL)
VALUES (BOARD_SEQ.NEXTVAL, 'KKW', '1234', '김기원', '01012345678', 'ADMIN')
DELETE FROM BMEMBER WHERE ID = 'KKW' --무결성 침범
ALTER TABLE BMEMBER ADD MUPDATE DATE NOT NULL
ALTER TABLE BMEMBER DROP COLUMN MUPDATE 
ALTER TABLE BMEMBER ADD MUPDATE DATE
ALTER TABLE BMEMBER RENAME COLUMN REGIST TO MREGISTS
ALTER TABLE BMEMBER RENAME COLUMN MREGIST TO REGIST




CREATE TABLE COMT(
	CNO NUMBER(10) PRIMARY KEY,
	CCONTENT VARCHAR2(1000) NOT NULL,
	MNO NUMBER(10) REFERENCES BMEMBER(MNO),
	CDATE DATE DEFAULT SYSDATE NOT NULL
)
SELECT * FROM COMT
DROP TABLE COMT
INSERT INTO COMT (CNO, CCONTENT, MNO)
VALUES(BOARD_SEQ.NEXTVAL, '댓글 테스트', 1)
DELETE FROM COMT

CREATE TABLE BOARD (
	 BNO NUMBER(10) PRIMARY KEY,
 	 BTITLE VARCHAR2(20) NOT NULL,
	 BCONTENT VARCHAR2(1000) NOT NULL,
	 MNO NUMBER(10) REFERENCES BMEMBER(MNO),
	 BDATE DATE DEFAULT SYSDATE NOT NULL,
	 BUPDATE DATE, 
	 CNO NUMBER(10) REFERENCES COMT(CNO)
 )
SELECT * FROM BOARD
DROP TABLE  BOARD
INSERT INTO BOARD (BNO, BTITLE, BCONTENT, MNO, BUPDATE, CNO)
VALUES(BOARD_SEQ.NEXTVAL, 'BOARD제목', 'BOARD내용', 1, SYSDATE, 3)
DELETE FROM BOARD


CREATE TABLE BOARD_BIN
 	AS SELECT * FROM BOARD WHERE  1<>1
 ALTER TABLE BOARD_BIN RENAME COLUMN BUPDATE TO BCUTDATE
 SELECT * FROM BOARD_BIN
 DROP TABLE BOARD_BIN
 DELETE FROM BOARD_BIN
 