CREATE USER BOARDTEST IDENTIFIED BY BOARDTEST
GRANT  CONNECT, RESOURCE  TO  BOARDTEST

ALTER USER BOARDTEST DEFAULT TABLESPACE USERS
ALTER USER BOARDTEST TEMPORARY TABLESPACE TEMP
DROP USER BOARDTEST
