--실행은 블럭 설정하고 ALT+C로 줄 단위로 실행한다.

CREATE USER JDBCTEST IDENTIFIED BY JDBCTEST
GRANT RESOURCE, CONNECT TO JDBCTEST
ALTER USER JDBCTEST DEFAULT TABLESPACE USERS
--JDBC 계정이 사용될 기본 데이터 베이스는 USERS
ALTER USER JDBCTEST TEMPORARY TABLESPACE TEMP
--JDBC 계정이 임시로 사용할 데이터베이스는 TEMP로 지정

