CREATE TABLE TEMP1 (COL1 VARCHAR2(20), COL2 VARCHAR2(20) );
INSERT INTO TEMP1 VALUES ('USER', 'GRANT_TEST');
SELECT * FROM TEMP1;
CREATE TABLE TEMP2 (COL1 VARCHAR2(20) );
DROP TABLE TEMP2;

SELECT * FROM SCOTT.TEMP;
INSERT INTO SCOTT.TEMP VALUES('TEXT', 'FROM ORCL_STUDY');
SELECT * FROM SCOTT.TEMP;
COMMIT;
SELECT * FROM SCOTT.TEMP;



--SYSTEM 주축 부여된 롤과 권한 확인
SELECT * FROM USER_SYS_PRIVS;
SELECT * FROM USER_ROLE_PRIVS;

