CREATE TABLE EMP (
	NUM NUMBER(3) PRIMARY KEY, 
	NAME VARCHAR2(15) NOT NULL,
	DEPT VARCHAR2(15) NOT NULL,
	SCORE NUMBER(7,2)
	);
	

SELECT * FROM EMP

CREATE SEQUENCE EMP_SEQ INCREMENT BY 1 START WITH 1  NOCACHE  NOCYCLE

INSERT INTO EMP (NUM, NAME, DEPT, SCORE)
VALUES(EMP_SEQ.NEXTVAL, '이름1','부서1', 10.0)

SELECT * FROM EMP
